application: ae-12-ajax
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /_ah/admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /reset
  script: index.py
  login: admin
  
- url: /.*
  script: index.py
